name: 'Chef Install'
author: 'Jason Field'
description: 'Installs Chef on your linux build agent with ease'
inputs:
  suite:
    description: 'Which suite to run'
    required: true
  os:
    description: 'Operating System to run tests on'
    required: true
runs: 
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'tool'
  color: 'red'
